#!/bin/bash
#SBATCH --cpus-per-task=16
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=02:00:00
#SBATCH --job-name=atm_diagnostics
#SBATCH --mem=100G
#SBATCH --error=atm_diagnostics.err.%J
#SBATCH --output=atm_diagnostics.out.%J
#SBATCH --account=phys034924

##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########

if [ ! -e /user/home/xz20153/CESM_postprocessing/cesm-env2/bin ]; then
    echo "*************************************************************************************"
    echo "CESM atm_diagnostics exiting due to non-existant python virtual environment in"
    echo "    /user/home/xz20153/CESM_postprocessing/cesm-env2/bin"
    echo "You must first run:"
    echo "$POSTPROCESS_PATH/create_python_env -machine [machine]"
    echo "*************************************************************************************"
    exit
fi


module purge




## load the boot-strap modules FIRST, before activating venv


module load languages/python/3.8.20

module load gcc/12.3.0-sknc

module load openmpi/5.0.3-et6p

module load netcdf-c/4.9.2-abpn

module load netcdf-fortran/4.6.1-nwqu


## Set LD_LIBRARY_PATH to ensure mpi4py can find MPI libraries
export LD_LIBRARY_PATH=/software/spack/linux-rocky8-broadwell/gcc-12.3.0/openmpi-5.0.3-et6p/lib:$LD_LIBRARY_PATH

## activate the virtualenv that contains all the non-bootstrapped dependencies

cd /user/home/xz20153/CESM_postprocessing/cesm-env2/bin
echo "Running from virtualenv directory:"
pwd
. activate




today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/user/home/xz20153/my_cesm_sandbox/testcase4/postprocess/logs/atm_diagnostics.log.$today


cd /user/home/xz20153/my_cesm_sandbox/testcase4/postprocess
mpirun -np 16 --bind-to none atm_diags_generator.py --debug 0  --caseroot /user/home/xz20153/my_cesm_sandbox/testcase4/postprocess >> ${log_filename} 2>&1

